openapi: 3.0.9
info:
  title: GPT Plugin
  version: 1.0.0
servers:
  - url: http://localhost:3003/api
    description: Development server
paths:
  /hello:
    get:
      summary: Say hello
      description: Say hello from the Plugin
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    operationId: sayHello
